#!/usr/bin/env python3
"""Generate signalnest/generated_routes.py from the route catalog."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "catalog" / "routes.json"
OUTPUT = ROOT / "signalnest" / "generated_routes.py"


def render(routes: dict[str, str]) -> str:
    lines = [
        "# Generated by tools/build_routes.py from catalog/routes.json.\n",
        "# Do not edit directly.\n\n",
        "ROUTES = {\n",
    ]
    lines.extend(f"    {key!r}: {routes[key]!r},\n" for key in sorted(routes))
    lines.append("}\n")
    return "".join(lines).replace("'", '"')


def load_routes() -> dict[str, str]:
    routes = json.loads(SOURCE.read_text(encoding="utf-8"))
    if (not isinstance(routes, dict) or not routes
            or not all(isinstance(key, str) and isinstance(value, str)
                       for key, value in routes.items())):
        raise SystemExit("catalog/routes.json must map strings to strings")
    return routes


def main() -> int:
    OUTPUT.write_text(render(load_routes()), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
