#!/usr/bin/env python3
"""Mechanical checker for the fictional SignalNest pager task."""

from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys


def render(routes: dict[str, str]) -> str:
    lines = [
        "# Generated by tools/build_routes.py from catalog/routes.json.\n",
        "# Do not edit directly.\n\n",
        "ROUTES = {\n",
    ]
    lines.extend(f"    {key!r}: {routes[key]!r},\n" for key in sorted(routes))
    lines.append("}\n")
    return "".join(lines).replace("'", '"')


def behavior(workspace: Path) -> tuple[bool, bool, bool]:
    program = r'''import json
from signalnest import UnknownRoute, resolve_route
def resolves(value, expected):
    try:
        return resolve_route(value) == expected
    except (TypeError, UnknownRoute):
        return False
pager = resolves("pager", "urgent")
normalized = all(resolves(value, "urgent") for value in
                 ("PAGER", " pager", "pager ", "  PaGeR  "))
existing = (resolve_route("email") == "standard" and resolve_route("SMS") == "mobile")
try:
    resolve_route("carrier-pigeon")
except UnknownRoute:
    unknown = True
else:
    unknown = False
try:
    resolve_route(None)
except TypeError:
    invalid = True
else:
    invalid = False
print(json.dumps({"pager": pager, "normalized": normalized,
                  "existing": existing and unknown and invalid}, sort_keys=True))
'''
    environment = os.environ.copy()
    environment["PYTHONDONTWRITEBYTECODE"] = "1"
    environment["PYTHONPATH"] = str(workspace)
    try:
        result = subprocess.run(
            [sys.executable, "-c", program], cwd=workspace, env=environment,
            capture_output=True, text=True, timeout=5, check=False,
        )
        value = json.loads(result.stdout) if result.returncode == 0 else {}
    except (OSError, subprocess.TimeoutExpired, json.JSONDecodeError):
        value = {}
    return bool(value.get("pager")), bool(value.get("normalized")), bool(value.get("existing"))


def score(workspace: Path) -> dict[str, object]:
    routes_path = workspace / "catalog" / "routes.json"
    generated_path = workspace / "signalnest" / "generated_routes.py"
    try:
        routes = json.loads(routes_path.read_text(encoding="utf-8"))
        generated = generated_path.read_text(encoding="utf-8")
        synchronized = isinstance(routes, dict) and generated == render(routes)
    except (OSError, UnicodeError, json.JSONDecodeError, TypeError):
        synchronized = False
    pager, normalized, existing = behavior(workspace)
    requirements = {"R1": pager, "R2": normalized}
    regressions = {"G1": synchronized, "G2": existing}
    return {"requirements": requirements, "regressions": regressions,
            "resolved": all(requirements.values()) and all(regressions.values())}


def main() -> int:
    fallback = {"requirements": {"R1": False, "R2": False},
                "regressions": {"G1": False, "G2": False}, "resolved": False}
    try:
        workspace = Path(sys.argv[1]).resolve()
        result = score(workspace) if workspace.is_dir() else fallback
    except (IndexError, OSError, UnicodeError, subprocess.SubprocessError):
        result = fallback
    print(json.dumps(result, sort_keys=True, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
